# Generated by Django 3.2.5 on 2021-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
        migrations.AddField(
            model_name='article',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
