# Generated by Django 3.2.5 on 2021-07-24 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
