# Generated by Django 3.2.5 on 2021-07-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
